<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/response.proto

namespace Zomato\VernacularService\Metadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7020a1470726f746f2f726573706f6e73652e70726f746f12117a6f6d" .
            "61746f2e7665726e6163756c617222320a054572726f7212120a0a657272" .
            "6f725f636f646518012001280412150a0d6572726f725f6d657373616765" .
            "18022001280922490a0e526573706f6e7365537461747573120e0a067374" .
            "6174757318012001280912270a056572726f7218022001280b32182e7a6f" .
            "6d61746f2e7665726e6163756c61722e4572726f724284015a4367697468" .
            "75622e636f6d2f5a6f6d61746f2f7665726e6163756c61722d7365727669" .
            "63652d636c69656e742d676f6c616e672f70726f746f2f7665726e616375" .
            "6c6172ca02185a6f6d61746f5c5665726e6163756c617253657276696365" .
            "e202215a6f6d61746f5c5665726e6163756c6172536572766963655c4d65" .
            "746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

