<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/vernacular.proto

namespace Zomato\VernacularService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * InsertLocalizedData contains localized data from a given text
 *
 * Generated from protobuf message <code>zomato.vernacular.InsertLocalizedData</code>
 */
class InsertLocalizedData extends \Google\Protobuf\Internal\Message
{
    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string original = 1;</code>
     */
    private $original = '';
    /**
     * lang_code is the language code in the original string is converted
     *
     * Generated from protobuf field <code>string lang_code = 2;</code>
     */
    private $lang_code = '';
    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string translation = 3;</code>
     */
    private $translation = '';
    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string transliteration = 4;</code>
     */
    private $transliteration = '';
    /**
     * localized_text is localized version of the original text
     *
     * Generated from protobuf field <code>string final = 5;</code>
     */
    private $final = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $original
     *           text is an original text
     *     @type string $lang_code
     *           lang_code is the language code in the original string is converted
     *     @type string $translation
     *           text is an original text
     *     @type string $transliteration
     *           text is an original text
     *     @type string $final
     *           localized_text is localized version of the original text
     * }
     */
    public function __construct($data = NULL) {
        \Zomato\VernacularService\Metadata\Vernacular::initOnce();
        parent::__construct($data);
    }

    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string original = 1;</code>
     * @return string
     */
    public function getOriginal()
    {
        return $this->original;
    }

    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string original = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginal($var)
    {
        GPBUtil::checkString($var, True);
        $this->original = $var;

        return $this;
    }

    /**
     * lang_code is the language code in the original string is converted
     *
     * Generated from protobuf field <code>string lang_code = 2;</code>
     * @return string
     */
    public function getLangCode()
    {
        return $this->lang_code;
    }

    /**
     * lang_code is the language code in the original string is converted
     *
     * Generated from protobuf field <code>string lang_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLangCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang_code = $var;

        return $this;
    }

    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string translation = 3;</code>
     * @return string
     */
    public function getTranslation()
    {
        return $this->translation;
    }

    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string translation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTranslation($var)
    {
        GPBUtil::checkString($var, True);
        $this->translation = $var;

        return $this;
    }

    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string transliteration = 4;</code>
     * @return string
     */
    public function getTransliteration()
    {
        return $this->transliteration;
    }

    /**
     * text is an original text
     *
     * Generated from protobuf field <code>string transliteration = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTransliteration($var)
    {
        GPBUtil::checkString($var, True);
        $this->transliteration = $var;

        return $this;
    }

    /**
     * localized_text is localized version of the original text
     *
     * Generated from protobuf field <code>string final = 5;</code>
     * @return string
     */
    public function getFinal()
    {
        return $this->final;
    }

    /**
     * localized_text is localized version of the original text
     *
     * Generated from protobuf field <code>string final = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFinal($var)
    {
        GPBUtil::checkString($var, True);
        $this->final = $var;

        return $this;
    }

}

