<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rpc.proto

namespace Zomato\VernacularService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Empty message for an rpc which doesn't take any input
 *
 * Generated from protobuf message <code>zomato.vernacular.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Zomato\VernacularService\Metadata\Rpc::initOnce();
        parent::__construct($data);
    }

}

