<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/vernacular.proto

namespace Zomato\VernacularService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RequestBulkInsertLocalizedData holds parameters required for bulk insert localized data rpc
 *
 * Generated from protobuf message <code>zomato.vernacular.RequestBulkInsertLocalizedData</code>
 */
class RequestBulkInsertLocalizedData extends \Google\Protobuf\Internal\Message
{
    /**
     * data holds the localized data to be inserted
     *
     * Generated from protobuf field <code>repeated .zomato.vernacular.InsertLocalizedData data = 1;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zomato\VernacularService\InsertLocalizedData[]|\Google\Protobuf\Internal\RepeatedField $data
     *           data holds the localized data to be inserted
     * }
     */
    public function __construct($data = NULL) {
        \Zomato\VernacularService\Metadata\Vernacular::initOnce();
        parent::__construct($data);
    }

    /**
     * data holds the localized data to be inserted
     *
     * Generated from protobuf field <code>repeated .zomato.vernacular.InsertLocalizedData data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * data holds the localized data to be inserted
     *
     * Generated from protobuf field <code>repeated .zomato.vernacular.InsertLocalizedData data = 1;</code>
     * @param \Zomato\VernacularService\InsertLocalizedData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zomato\VernacularService\InsertLocalizedData::class);
        $this->data = $arr;

        return $this;
    }

}

