<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/response.proto

namespace Zomato\VernacularService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ResponseStatus holds status of RPC's response
 *
 * Generated from protobuf message <code>zomato.vernacular.ResponseStatus</code>
 */
class ResponseStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * status of response, EX: success
     *
     * Generated from protobuf field <code>string status = 1;</code>
     */
    private $status = '';
    /**
     * error if request wasn't successful
     *
     * Generated from protobuf field <code>.zomato.vernacular.Error error = 2;</code>
     */
    private $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *           status of response, EX: success
     *     @type \Zomato\VernacularService\Error $error
     *           error if request wasn't successful
     * }
     */
    public function __construct($data = NULL) {
        \Zomato\VernacularService\Metadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * status of response, EX: success
     *
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * status of response, EX: success
     *
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * error if request wasn't successful
     *
     * Generated from protobuf field <code>.zomato.vernacular.Error error = 2;</code>
     * @return \Zomato\VernacularService\Error
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * error if request wasn't successful
     *
     * Generated from protobuf field <code>.zomato.vernacular.Error error = 2;</code>
     * @param \Zomato\VernacularService\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Zomato\VernacularService\Error::class);
        $this->error = $var;

        return $this;
    }

}

