<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/vernacular.proto

namespace Zomato\VernacularService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ResponseLocalizationData holds response payload of BulkGetLocalizationData
 *
 * Generated from protobuf message <code>zomato.vernacular.ResponseLocalizationData</code>
 */
class ResponseLocalizationData extends \Google\Protobuf\Internal\Message
{
    /**
     * status holds RPCs status
     *
     * Generated from protobuf field <code>.zomato.vernacular.ResponseStatus status = 1;</code>
     */
    private $status = null;
    /**
     * localized_texts is an ordered array containing localized data
     *
     * Generated from protobuf field <code>repeated .zomato.vernacular.LocalizedText localized_texts = 2;</code>
     */
    private $localized_texts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zomato\VernacularService\ResponseStatus $status
     *           status holds RPCs status
     *     @type \Zomato\VernacularService\LocalizedText[]|\Google\Protobuf\Internal\RepeatedField $localized_texts
     *           localized_texts is an ordered array containing localized data
     * }
     */
    public function __construct($data = NULL) {
        \Zomato\VernacularService\Metadata\Vernacular::initOnce();
        parent::__construct($data);
    }

    /**
     * status holds RPCs status
     *
     * Generated from protobuf field <code>.zomato.vernacular.ResponseStatus status = 1;</code>
     * @return \Zomato\VernacularService\ResponseStatus
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * status holds RPCs status
     *
     * Generated from protobuf field <code>.zomato.vernacular.ResponseStatus status = 1;</code>
     * @param \Zomato\VernacularService\ResponseStatus $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Zomato\VernacularService\ResponseStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * localized_texts is an ordered array containing localized data
     *
     * Generated from protobuf field <code>repeated .zomato.vernacular.LocalizedText localized_texts = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocalizedTexts()
    {
        return $this->localized_texts;
    }

    /**
     * localized_texts is an ordered array containing localized data
     *
     * Generated from protobuf field <code>repeated .zomato.vernacular.LocalizedText localized_texts = 2;</code>
     * @param \Zomato\VernacularService\LocalizedText[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocalizedTexts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zomato\VernacularService\LocalizedText::class);
        $this->localized_texts = $arr;

        return $this;
    }

}

